# Generated by Django 5.1 on 2024-11-25 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_chatrequest_trocafeita_delete_troca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensagem', models.TextField(max_length=300, verbose_name='Mensagem da solicitação')),
                ('dataTroca', models.DateTimeField(auto_now_add=True, verbose_name='Data da Troca')),
                ('status', models.CharField(default='Concluída', max_length=50, verbose_name='Status da troca')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.livro', verbose_name='Livro da troca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que solicitou')),
                ('usuarioDestino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_usuarioDestino', to=settings.AUTH_USER_MODEL, verbose_name='Usuário alvo')),
            ],
            options={
                'verbose_name': 'Histórico de Troca',
                'verbose_name_plural': 'Histórico de Trocas',
                'ordering': ['-dataTroca'],
            },
        ),
    ]
