# Generated by Django 5.1 on 2024-11-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_perfil_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
    ]
