# Generated by Django 5.1 on 2024-11-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_perfil_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
    ]
