# Generated by Django 5.1 on 2024-11-25 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_perfil_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.livro'),
        ),
    ]
